// Generated by CoffeeScript 1.7.1
(function() {
  var gameWon, message, sayHello;

  sayHello = function(name) {
    return alert("Hello " + name);
  };


  /*
  This is a comment in JS
   */

  if (sayHello() === true) {
    alert("It's on");
  }

  gameWon = true;

  if (!gameWon) {
    alert("It's all over");
  }

  if (gameWon) {
    alert("Hi");
  }

  message = (function() {
    switch (cupsOfCoffee) {
      case 0:
        return go('Asleep');
      case 1:
        return go('Awake');
      case 2:
        return go('Asleep again');
      default:
        return go('Dead');
    }
  })();

  if (typeof coffeePot !== "undefined" && coffeePot !== null) {
    coffeePot.brew();
  }

  message = (function() {
    switch (newLevel) {
      case 1:
        return 'Out of bed yet?';
      case 2:
        return 'Good  morning!';
      default:
        return 'You should stop while you can';
    }
  })();

  if (gameWon == null) {
    gameWon = 10;
  }

}).call(this);
